services:
  db:
    image: mysql:8.0
    container_name: hospital-mysql
    restart: always
    environment:
      MSYQL_USER: root
      MYSQL_PASSWORD: ChangeMe123!
      MYSQL_ROOT_PASSWORD: ChangeMe123!
      MYSQL_DATABASE: hospitaldb
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data:
  